name: Free VPS without Ngrok
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup VPS
      run: |
        echo "Setting up VPS..."
        # به‌روزرسانی بسته‌ها
        sudo apt-get update
        # نصب openssh-server
        sudo apt-get install -y openssh-server
        # پیکربندی SSH
        sudo mkdir -p /var/run/sshd
        sudo systemctl enable ssh --now
        # بررسی وضعیت SSH
        sudo systemctl status ssh
        echo "SSH server started on port 22!"
        # نصب وب‌سرور Nginx
        sudo apt-get install -y nginx
        sudo systemctl start nginx
        sudo systemctl status nginx
        echo "Nginx web server started on port 80!"
        # تست دسترسی به وب‌سرور
        curl localhost || echo "Failed to access Nginx"
        # نگه داشتن سرور فعال
        while true; do sleep 1000; done
